# Site settings
locale: "fr-FR"
title: Sandrine Henry
email: eleonore.henry@gmail.com
description: Data Science Portfolio
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://sandrineh.github.io" # the base hostname & protocol for your site
author:
street_address: #1234 Somewhere Road
city: Paris
state: #TN
zip_code: #55555
country: France
phone: #(716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/sandrineh
gitlab_url: #https://gitlab.com/u/andrewbanchich
googleplus_url: #https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/hyssey/
linkedin_url: https://www.linkedin.com/in/sandrine-e-henry/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/eleonore_h

# Build settings
markdown: kramdown

sass:
style: compressed
